// User Types
export const PHONE_VERIFY = "PHONE_VERIFY";
export const PHONE_VERIFY_FAILED = "PHONE_VERIFY_FAILED";
export const PHONE_VERIFY_START = "PHONE_VERIFY_START";
export const PHONE_OTP_VERIFY = "PHONE_OTP_VERIFY";
export const PHONE_OTP_VERIFY_FAILED = "PHONE_OTP_VERIFY_FAILED";
export const BASIC_INFO = "BASIC_INFO";
export const BASIC_INFO_FAILED = "BASIC_INFO_FAILED";
export const TAB_BAR_VISIBILITY = "TAB_BAR_VISIBILITY";
export const USER_PROFILE_IMAGE = "USER_PROFILE_IMAGE";

//Profile Types
export const COUNTRY_NAME = "COUNTRY_NAME";
export const CURRENCY_NAME = "CURRENCY_NAME";
export const PROFILE_DATA = "PROFILE_DATA";
export const PROFILE_DATA_FAILED = "PROFILE_DATA_FAILED";
export const GET_REFER_FRIENDS = "GET_REFER_FRIENDS";
export const GET_REFER_FRIENDS_ERROR = "GET_REFER_FRIENDS_ERROR";
export const REFER_FRIENDS_API = "REFER_FRIENDS_API";
export const REFER_FRIENDS_FAILED = "REFER_FRIENDS_FAILED";
export const PAYMENT_METHODS_DATA = "PAYMENT_METHODS_DATA";
export const PAYMENT_METHODS_DATA_FAILED = "PAYMENT_METHODS_DATA_FAILED";
export const PAYMENT_FORM_VISIBILITY = "PAYMENT_FORM_VISIBILITY";
export const PAYOUT_METHODS_DATA = "PAYOUT_METHODS_DATA";
export const ADD_PAYOUT_METHOD_SUCCESS = "ADD_PAYOUT_METHOD_SUCCESS";
export const ADD_PAYOUT_METHOD_FAILED = "ADD_PAYOUT_METHOD_FAILED";
export const PAYMENT_HISTORY = "PAYMENT_HISTORY";
export const PAYOUT_HISTORY = "PAYOUT_HISTORY";
export const PROFILE_IMAGES = "PROFILE_IMAGES";
export const PAYOUT_ADDRESS = "PAYOUT_ADDRESS";

//Listing Types
export const PLACE_TYPE = "PLACE_TYPE";
export const GUEST_PLACE_TYPE = "GUEST_PLACE_TYPE";
export const PLACE_LOCATION = "PLACE_LOCATION";
export const PLACE_INFO = "PLACE_INFO";
export const PLACE_PHOTOS = "PLACE_PHOTOS";
export const PLACE_TITLE = "PLACE_TITLE";
export const PLACE_DESC = "PLACE_DESC";
export const PLACE_AMENITIES = "PLACE_AMENITIES";

export const PLACE_PRICE = "PLACE_PRICE";
export const PLACE_DATE = "PLACE_DATE";
export const GET_USER_LIST = "GET_USER_LIST";
export const GET_SINGLE_LISTINGS = "GET_SINGLE_LISTINGS";
export const MASTER_DATA = "MASTER_DATA";
export const MASTER_DATA_HIGHLIGHTS = "MASTER_DATA_HIGHLIGHTS";
export const EDIT_USER_LISTINGS = "EDIT_USER_LISTINGS";
export const INFO_FOR_GUESTS = "INFO_FOR_GUESTS";

// Feed list Type
export const ADD_FEED_LIST = "ADD_FEED_LIST";
export const BOOK_HOTEL = "BOOK_HOTEL";
export const FILTERED_RESULTS = "FILTERED_RESULTS";
export const FILTER_OBJ = "FILTER_OBJ";
export const PLAIN_FILTER = "PLAIN_FILTER";
export const UNREAD_MESSAGE_COUNT = "UNREAD_MESSAGE_COUNT";
export const RELEVANT = "RELEVANT";
export const MAP_LOCATION = "MAP_LOCATION";
export const FEED_LOADING = "FEED_LOADING";
export const CURRENT_LOCATION = "CURRENT_LOCATION";

// Reservations
export const RESERVATIONS_ALL = "RESERVATIONS_ALL";
export const RESERVATIONS_SINGLE_SUMMARY = "RESERVATIONS_SINGLE_SUMMARY";
export const RESERVATION_LOADING = "RESERVATION_LOADING";
export const RESERVATION_TYPE = "RESERVATION_TYPE";

//Bookings
export const BOOKINGS_ALL = "BOOKINGS_ALL";
export const BOOKINGS_TYPE = "BOOKINGS_TYPE";

//travel plan
export const PLAN_ALL = "PLAN_ALL";
export const ALL_LOCATIONS = "ALL_LOCATIONS";
export const WORLD_TRAVEL_PLANS = "WORLD_TRAVEL_PLANS";
export const SLIDER_VALUE = "SLIDER_VALUE";
export const TRAVEL_PLANS_LOADING = "TRAVEL_PLANS_LOADING";
export const OPTION_BUTTON_STATUS = "OPTION_BUTTON_STATUS";
export const FILTER_TYPE = "FILTER_TYPE";

//Chats
export const ALL_CHATS = "ALL_CHATS";
export const USER_CHATS = "USER_CHATS";
export const ALL_NOTIFICATIONS = "ALL_NOTIFICATIONS";
